"use client"

import type React from "react"
import { createContext, useContext, useState } from "react"

type Language = "en" | "id" | "ja" | "zh" | "es" | "fr" | "ko" | "vi"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    "app.title": "MarkVault",
    "app.subtitle": "Professional image protection with intelligent watermarking",
    "upload.title": "Upload Image",
    "upload.drag": "Drag and drop your image here",
    "upload.click": "or click to browse",
    "upload.error.type": "Please upload a valid image file (JPG, PNG, GIF, WebP, SVG)",
    "upload.error.size": "File size must be less than 10MB",
    "edit.title": "Edit Image",
    "preview.title": "Preview",
    "preview.download": "Download Protected Image",
    "bw.label": "Convert to Black & White",
    "watermark.label": "Add Watermark Pattern",
    "watermark.text": "Watermark Text",
    "watermark.fontSize": "Font Size",
    "watermark.color": "Watermark Color",
    "watermark.opacity": "Opacity",
    "watermark.gap": "Gap Between Watermarks",
    "watermark.rotation": "Rotation Angle",
    "watermark.offsetX": "Offset X",
    "watermark.offsetY": "Offset Y",
    "watermark.note": "Watermarks are permanently embedded in the exported image",
    "tab.bw": "Black & White",
    "tab.watermark": "Watermark",
    "common.reset": "Reset",
    "landing.badge": "Professional Image Protection",
    "landing.hero.title": "Protect Your Images with Intelligent Watermarking",
    "landing.hero.subtitle":
      "Add professional watermarks and convert images to black & white. Secure your visual content with permanent, embedded protection.",
    "landing.hero.cta": "Get Started Free",
    "landing.hero.learn": "Learn More",
    "landing.features.title": "Powerful Features",
    "landing.features.protection": "Permanent Protection",
    "landing.features.protectionDesc":
      "Watermarks are permanently embedded in your images, ensuring they cannot be removed or edited.",
    "landing.features.fast": "Lightning Fast",
    "landing.features.fastDesc": "Process your images instantly with our optimized client-side technology.",
    "landing.features.secure": "100% Secure",
    "landing.features.secureDesc": "All processing happens on your device. Your images never leave your computer.",
    "landing.features.watermark": "Custom Watermarks",
    "landing.features.watermarkDesc": "Create diagonal watermark patterns with full customization options.",
    "landing.features.bw": "Black & White",
    "landing.features.bwDesc": "Convert your images to stunning black and white with a single click.",
    "landing.features.multilang": "8 Languages",
    "landing.features.multilangDesc":
      "Available in English, Indonesian, Japanese, Chinese, Spanish, French, Korean, and Vietnamese.",
    "landing.details.title": "About MarkVault",
    "landing.details.description":
      "MarkVault is a professional image protection tool designed for photographers, content creators, and businesses who want to safeguard their visual assets. With intelligent watermarking and image processing capabilities, MarkVault ensures your images remain protected.",
    "landing.details.feature1": "Diagonal watermark patterns with customizable spacing and rotation",
    "landing.details.feature2": "Convert images to black and white with professional quality",
    "landing.details.feature3": "Multi-language support for global users",
    "landing.details.version": "Current Version",
    "landing.details.released": "Released",
    "landing.details.status": "Status",
    "landing.contact.title": "Get in Touch",
    "landing.contact.subtitle":
      "Have questions or feedback? We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    "landing.contact.name": "Your Name",
    "landing.contact.namePlaceholder": "John Doe",
    "landing.contact.email": "Your Email",
    "landing.contact.emailPlaceholder": "john@example.com",
    "landing.contact.message": "Message",
    "landing.contact.messagePlaceholder": "Tell us what you think about MarkVault...",
    "landing.contact.send": "Send Message",
    "landing.footer": "© 2025 MarkVault. All rights reserved. Professional image protection for everyone.",
    "learn.title": "Learn More",
    "learn.subtitle": "Complete documentation and guides for MarkVault",
    "learn.gettingStarted": "Getting Started",
    "learn.gettingStartedDesc": "Learn how to upload images and apply watermarks in just a few clicks.",
    "learn.watermarkGuide": "Watermark Guide",
    "learn.watermarkGuideDesc":
      "Master the art of creating professional watermark patterns with custom spacing and rotation.",
    "learn.bwConversion": "Black & White Conversion",
    "learn.bwConversionDesc": "Convert your images to stunning black and white with professional quality.",
    "learn.bestPractices": "Best Practices",
    "learn.bestPracticesDesc": "Tips and tricks for protecting your images effectively.",
    "learn.faq": "Frequently Asked Questions",
    "learn.faqDesc": "Find answers to common questions about MarkVault.",
    "learn.step1": "Step 1: Upload Your Image",
    "learn.step1Desc":
      "Click the upload area or drag and drop your image. Supported formats: JPG, PNG, GIF, WebP, SVG. Maximum file size: 10MB.",
    "learn.step2": "Step 2: Configure Watermark",
    "learn.step2Desc":
      "Enter your watermark text and customize the appearance with font size, color, and opacity settings.",
    "learn.step3": "Step 3: Adjust Pattern",
    "learn.step3Desc":
      "Set the gap between watermarks, rotation angle, and position offsets to create your desired pattern.",
    "learn.step4": "Step 4: Apply Effects",
    "learn.step4Desc": "Optionally convert your image to black and white for a classic look.",
    "learn.step5": "Step 5: Download",
    "learn.step5Desc": "Download your protected image. Watermarks are permanently embedded and cannot be removed.",
    "learn.watermarkTip1": "Diagonal Patterns",
    "learn.watermarkTip1Desc":
      "Use a -45 degree rotation for classic diagonal watermarks that are difficult to remove.",
    "learn.watermarkTip2": "Opacity Settings",
    "learn.watermarkTip2Desc": "Set opacity between 20-40% for visible protection without obscuring the image content.",
    "learn.watermarkTip3": "Custom Spacing",
    "learn.watermarkTip3Desc": "Adjust gap spacing from 50-300px depending on your image size and protection needs.",
    "learn.bwTip1": "Professional Look",
    "learn.bwTip1Desc": "Black and white conversion gives images a timeless, professional appearance.",
    "learn.bwTip2": "Enhanced Contrast",
    "learn.bwTip2Desc": "B&W images often have better contrast, making watermarks more visible.",
    "learn.bwTip3": "Reduced File Size",
    "learn.bwTip3Desc": "Grayscale images typically have smaller file sizes than color images.",
    "learn.faq1Q": "Can watermarks be removed?",
    "learn.faq1A":
      "No. MarkVault permanently embeds watermarks into the image data. They cannot be removed without destroying the image.",
    "learn.faq2Q": "Is my image data stored on servers?",
    "learn.faq2A": "No. All processing happens on your device. Your images never leave your computer.",
    "learn.faq3Q": "What image formats are supported?",
    "learn.faq3A": "MarkVault supports JPG, PNG, GIF, WebP, and SVG formats. Maximum file size is 10MB.",
    "learn.faq4Q": "Can I use MarkVault offline?",
    "learn.faq4A": "Yes. Once loaded, MarkVault works completely offline. No internet connection required.",
    "learn.faq5Q": "How do I choose the right watermark text?",
    "learn.faq5A":
      "Use your name, copyright symbol, website URL, or company name. Keep it short for better visibility.",
  },
  id: {
    "app.title": "MarkVault",
    "app.subtitle": "Perlindungan gambar profesional dengan watermarking cerdas",
    "upload.title": "Unggah Gambar",
    "upload.drag": "Seret dan lepas gambar Anda di sini",
    "upload.click": "atau klik untuk memilih",
    "upload.error.type": "Silakan unggah file gambar yang valid (JPG, PNG, GIF, WebP, SVG)",
    "upload.error.size": "Ukuran file harus kurang dari 10MB",
    "edit.title": "Edit Gambar",
    "preview.title": "Pratinjau",
    "preview.download": "Unduh Gambar Terlindungi",
    "bw.label": "Konversi ke Hitam & Putih",
    "watermark.label": "Tambahkan Pola Watermark",
    "watermark.text": "Teks Watermark",
    "watermark.fontSize": "Ukuran Font",
    "watermark.color": "Warna Watermark",
    "watermark.opacity": "Opasitas",
    "watermark.gap": "Jarak Antar Watermark",
    "watermark.rotation": "Sudut Rotasi",
    "watermark.offsetX": "Offset X",
    "watermark.offsetY": "Offset Y",
    "watermark.note": "Watermark tertanam permanen dalam gambar yang diekspor",
    "tab.bw": "Hitam & Putih",
    "tab.watermark": "Watermark",
    "common.reset": "Reset",
    "landing.badge": "Perlindungan Gambar Profesional",
    "landing.hero.title": "Lindungi Gambar Anda dengan Watermarking Cerdas",
    "landing.hero.subtitle":
      "Tambahkan watermark profesional dan konversi gambar ke hitam putih. Amankan konten visual Anda dengan perlindungan permanen yang tertanam.",
    "landing.hero.cta": "Mulai Gratis",
    "landing.hero.learn": "Pelajari Lebih Lanjut",
    "landing.features.title": "Fitur Canggih",
    "landing.features.protection": "Perlindungan Permanen",
    "landing.features.protectionDesc":
      "Watermark tertanam permanen dalam gambar Anda, memastikan tidak dapat dihapus atau diedit.",
    "landing.features.fast": "Sangat Cepat",
    "landing.features.fastDesc": "Proses gambar Anda secara instan dengan teknologi sisi klien kami yang dioptimalkan.",
    "landing.features.secure": "100% Aman",
    "landing.features.secureDesc":
      "Semua pemrosesan terjadi di perangkat Anda. Gambar Anda tidak pernah meninggalkan komputer Anda.",
    "landing.features.watermark": "Watermark Kustom",
    "landing.features.watermarkDesc": "Buat pola watermark diagonal dengan opsi kustomisasi penuh.",
    "landing.features.bw": "Hitam & Putih",
    "landing.features.bwDesc": "Konversi gambar Anda ke hitam putih yang menakjubkan dengan satu klik.",
    "landing.features.multilang": "8 Bahasa",
    "landing.features.multilangDesc":
      "Tersedia dalam Bahasa Inggris, Indonesia, Jepang, Cina, Spanyol, Prancis, Korea, dan Vietnam.",
    "landing.details.title": "Tentang MarkVault",
    "landing.details.description":
      "MarkVault adalah alat perlindungan gambar profesional yang dirancang untuk fotografer, kreator konten, dan bisnis yang ingin melindungi aset visual mereka. Dengan kemampuan watermarking cerdas dan pemrosesan gambar, MarkVault memastikan gambar Anda tetap terlindungi.",
    "landing.details.feature1": "Pola watermark diagonal dengan jarak dan rotasi yang dapat disesuaikan",
    "landing.details.feature2": "Konversi gambar ke hitam putih dengan kualitas profesional",
    "landing.details.feature3": "Dukungan multi-bahasa untuk pengguna global",
    "landing.details.version": "Versi Saat Ini",
    "landing.details.released": "Dirilis",
    "landing.details.status": "Status",
    "landing.contact.title": "Hubungi Kami",
    "landing.contact.subtitle":
      "Ada pertanyaan atau umpan balik? Kami ingin mendengar dari Anda. Kirimkan pesan dan kami akan merespons sesegera mungkin.",
    "landing.contact.name": "Nama Anda",
    "landing.contact.namePlaceholder": "John Doe",
    "landing.contact.email": "Email Anda",
    "landing.contact.emailPlaceholder": "john@example.com",
    "landing.contact.message": "Pesan",
    "landing.contact.messagePlaceholder": "Beritahu kami apa yang Anda pikirkan tentang MarkVault...",
    "landing.contact.send": "Kirim Pesan",
    "landing.footer": "© 2025 MarkVault. Semua hak dilindungi. Perlindungan gambar profesional untuk semua orang.",
    "learn.title": "Pelajari Lebih Lanjut",
    "learn.subtitle": "Dokumentasi lengkap dan panduan untuk MarkVault",
    "learn.gettingStarted": "Memulai",
    "learn.gettingStartedDesc": "Pelajari cara mengunggah gambar dan menerapkan watermark hanya dalam beberapa klik.",
    "learn.watermarkGuide": "Panduan Watermark",
    "learn.watermarkGuideDesc": "Kuasai seni membuat pola watermark profesional dengan jarak dan rotasi khusus.",
    "learn.bwConversion": "Konversi Hitam & Putih",
    "learn.bwConversionDesc": "Konversi gambar Anda ke hitam putih yang menakjubkan dengan kualitas profesional.",
    "learn.bestPractices": "Praktik Terbaik",
    "learn.bestPracticesDesc": "Tips dan trik untuk melindungi gambar Anda secara efektif.",
    "learn.faq": "Pertanyaan yang Sering Diajukan",
    "learn.faqDesc": "Temukan jawaban atas pertanyaan umum tentang MarkVault.",
    "learn.step1": "Langkah 1: Unggah Gambar Anda",
    "learn.step1Desc":
      "Klik area unggah atau seret dan lepas gambar Anda. Format yang didukung: JPG, PNG, GIF, WebP, SVG. Ukuran file maksimal: 10MB.",
    "learn.step2": "Langkah 2: Konfigurasi Watermark",
    "learn.step2Desc":
      "Masukkan teks watermark Anda dan sesuaikan tampilan dengan pengaturan ukuran font, warna, dan opasitas.",
    "learn.step3": "Langkah 3: Sesuaikan Pola",
    "learn.step3Desc":
      "Atur jarak antar watermark, sudut rotasi, dan offset posisi untuk membuat pola yang diinginkan.",
    "learn.step4": "Langkah 4: Terapkan Efek",
    "learn.step4Desc": "Secara opsional konversi gambar Anda ke hitam putih untuk tampilan klasik.",
    "learn.step5": "Langkah 5: Unduh",
    "learn.step5Desc": "Unduh gambar yang dilindungi. Watermark tertanam permanen dan tidak dapat dihapus.",
    "learn.watermarkTip1": "Pola Diagonal",
    "learn.watermarkTip1Desc": "Gunakan rotasi -45 derajat untuk watermark diagonal klasik yang sulit dihapus.",
    "learn.watermarkTip2": "Pengaturan Opasitas",
    "learn.watermarkTip2Desc":
      "Atur opasitas antara 20-40% untuk perlindungan yang terlihat tanpa mengaburkan konten gambar.",
    "learn.watermarkTip3": "Jarak Khusus",
    "learn.watermarkTip3Desc":
      "Sesuaikan jarak celah dari 50-300px tergantung ukuran gambar dan kebutuhan perlindungan Anda.",
    "learn.bwTip1": "Tampilan Profesional",
    "learn.bwTip1Desc": "Konversi hitam putih memberikan gambar tampilan yang abadi dan profesional.",
    "learn.bwTip2": "Kontras Ditingkatkan",
    "learn.bwTip2Desc": "Gambar B&W sering kali memiliki kontras yang lebih baik, membuat watermark lebih terlihat.",
    "learn.bwTip3": "Ukuran File Berkurang",
    "learn.bwTip3Desc": "Gambar skala abu-abu biasanya memiliki ukuran file lebih kecil daripada gambar berwarna.",
    "learn.faq1Q": "Bisakah watermark dihapus?",
    "learn.faq1A":
      "Tidak. MarkVault secara permanen menyematkan watermark ke dalam data gambar. Mereka tidak dapat dihapus tanpa merusak gambar.",
    "learn.faq2Q": "Apakah data gambar saya disimpan di server?",
    "learn.faq2A":
      "Tidak. Semua pemrosesan terjadi di perangkat Anda. Gambar Anda tidak pernah meninggalkan komputer Anda.",
    "learn.faq3Q": "Format gambar apa yang didukung?",
    "learn.faq3A": "MarkVault mendukung format JPG, PNG, GIF, WebP, dan SVG. Ukuran file maksimal adalah 10MB.",
    "learn.faq4Q": "Bisakah saya menggunakan MarkVault secara offline?",
    "learn.faq4A":
      "Ya. Setelah dimuat, MarkVault bekerja sepenuhnya offline. Tidak ada koneksi internet yang diperlukan.",
    "learn.faq5Q": "Bagaimana cara memilih teks watermark yang tepat?",
    "learn.faq5A":
      "Gunakan nama Anda, simbol hak cipta, URL situs web, atau nama perusahaan. Buat singkat untuk visibilitas yang lebih baik.",
  },
  ja: {
    "app.title": "MarkVault",
    "app.subtitle": "インテリジェントなウォーターマーク機能を備えたプロフェッショナル画像保護",
    "upload.title": "画像をアップロード",
    "upload.drag": "ここに画像をドラッグアンドドロップ",
    "upload.click": "またはクリックして参照",
    "upload.error.type": "有効な画像ファイルをアップロードしてください (JPG、PNG、GIF、WebP、SVG)",
    "upload.error.size": "ファイルサイズは10MB未満である必要があります",
    "edit.title": "画像を編集",
    "preview.title": "プレビュー",
    "preview.download": "保護された画像をダウンロード",
    "bw.label": "白黒に変換",
    "watermark.label": "ウォーターマークパターンを追加",
    "watermark.text": "ウォーターマークテキスト",
    "watermark.fontSize": "フォントサイズ",
    "watermark.color": "ウォーターマークの色",
    "watermark.opacity": "不透明度",
    "watermark.gap": "ウォーターマーク間のギャップ",
    "watermark.rotation": "回転角度",
    "watermark.offsetX": "オフセット X",
    "watermark.offsetY": "オフセット Y",
    "watermark.note": "ウォーターマークはエクスポートされた画像に永続的に埋め込まれます",
    "tab.bw": "白黒",
    "tab.watermark": "ウォーターマーク",
    "common.reset": "リセット",
    "landing.badge": "プロフェッショナル画像保護",
    "landing.hero.title": "インテリジェントなウォーターマークで画像を保護",
    "landing.hero.subtitle":
      "プロフェッショナルなウォーターマークを追加し、画像を白黒に変換します。永続的に埋め込まれた保護でビジュアルコンテンツを保護します。",
    "landing.hero.cta": "無料で始める",
    "landing.hero.learn": "詳細を学ぶ",
    "landing.features.title": "強力な機能",
    "landing.features.protection": "永続的な保護",
    "landing.features.protectionDesc": "ウォーターマークは画像に永続的に埋め込まれ、削除または編集できません。",
    "landing.features.fast": "超高速",
    "landing.features.fastDesc": "最適化されたクライアント側テクノロジーで画像を即座に処理します。",
    "landing.features.secure": "100%安全",
    "landing.features.secureDesc": "すべての処理はデバイス上で行われます。画像はコンピュータを離れません。",
    "landing.features.watermark": "カスタムウォーターマーク",
    "landing.features.watermarkDesc": "完全なカスタマイズオプション付きの対角ウォーターマークパターンを作成します。",
    "landing.features.bw": "白黒",
    "landing.features.bwDesc": "ワンクリックで画像を素晴らしい白黒に変換します。",
    "landing.features.multilang": "8言語",
    "landing.features.multilangDesc":
      "英語、インドネシア語、日本語、中国語、スペイン語、フランス語、韓国語、ベトナム語で利用可能です。",
    "landing.details.title": "MarkVaultについて",
    "landing.details.description":
      "MarkVaultは、写真家、コンテンツクリエーター、ビジュアルアセットを保護したいビジネス向けに設計されたプロフェッショナル画像保護ツールです。インテリジェントなウォーターマーク機能と画像処理機能により、MarkVaultは画像を保護します。",
    "landing.details.feature1": "カスタマイズ可能な間隔と回転を備えた対角ウォーターマークパターン",
    "landing.details.feature2": "プロフェッショナルな品質で画像を白黒に変換",
    "landing.details.feature3": "グローバルユーザー向けの多言語サポート",
    "landing.details.version": "現在のバージョン",
    "landing.details.released": "リリース日",
    "landing.details.status": "ステータス",
    "landing.contact.title": "お問い合わせ",
    "landing.contact.subtitle":
      "ご質問やご意見がありますか？ぜひお聞かせください。メッセージを送信いただければ、できるだけ早くお返事します。",
    "landing.contact.name": "お名前",
    "landing.contact.namePlaceholder": "John Doe",
    "landing.contact.email": "メールアドレス",
    "landing.contact.emailPlaceholder": "john@example.com",
    "landing.contact.message": "メッセージ",
    "landing.contact.messagePlaceholder": "MarkVaultについてのご意見をお聞かせください...",
    "landing.contact.send": "メッセージを送信",
    "landing.footer": "© 2025 MarkVault。著作権所有。すべての人のためのプロフェッショナル画像保護。",
    "learn.title": "詳細を学ぶ",
    "learn.subtitle": "MarkVaultの完全なドキュメントとガイド",
    "learn.gettingStarted": "はじめに",
    "learn.gettingStartedDesc": "わずか数クリックで画像をアップロードしてウォーターマークを適用する方法を学びます。",
    "learn.watermarkGuide": "ウォーターマークガイド",
    "learn.watermarkGuideDesc":
      "カスタム間隔と回転を使用してプロフェッショナルなウォーターマークパターンを作成する方法をマスターします。",
    "learn.bwConversion": "白黒変換",
    "learn.bwConversionDesc": "プロフェッショナルな品質で画像を素晴らしい白黒に変換します。",
    "learn.bestPractices": "ベストプラクティス",
    "learn.bestPracticesDesc": "画像を効果的に保護するためのヒントとコツ。",
    "learn.faq": "よくある質問",
    "learn.faqDesc": "MarkVaultに関するよくある質問への回答を見つけます。",
    "learn.step1": "ステップ1：画像をアップロード",
    "learn.step1Desc":
      "アップロード領域をクリックするか、画像をドラッグアンドドロップします。サポートされている形式：JPG、PNG、GIF、WebP、SVG。最大ファイルサイズ：10MB。",
    "learn.step2": "ステップ2：ウォーターマークを構成",
    "learn.step2Desc":
      "ウォーターマークテキストを入力し、フォントサイズ、色、不透明度の設定で外観をカスタマイズします。",
    "learn.step3": "ステップ3：パターンを調整",
    "learn.step3Desc": "ウォーターマーク間のギャップ、回転角度、位置オフセットを設定して、目的のパターンを作成します。",
    "learn.step4": "ステップ4：エフェクトを適用",
    "learn.step4Desc": "オプションで画像を白黒に変換してクラシックな外観にします。",
    "learn.step5": "ステップ5：ダウンロード",
    "learn.step5Desc":
      "保護された画像をダウンロードします。ウォーターマークは永続的に埋め込まれており、削除できません。",
    "learn.watermarkTip1": "対角パターン",
    "learn.watermarkTip1Desc": "-45度の回転を使用して、削除が難しいクラシックな対角ウォーターマークを作成します。",
    "learn.watermarkTip2": "不透明度設定",
    "learn.watermarkTip2Desc":
      "不透明度を20～40％に設定して、画像コンテンツを曇らせることなく目に見える保護を実現します。",
    "learn.watermarkTip3": "カスタム間隔",
    "learn.watermarkTip3Desc": "画像サイズと保護ニーズに応じて、ギャップ間隔を50～300pxに調整します。",
    "learn.bwTip1": "プロフェッショナルな外観",
    "learn.bwTip1Desc": "白黒変換は画像に時代を超えたプロフェッショナルな外観を与えます。",
    "learn.bwTip2": "コントラスト強化",
    "learn.bwTip2Desc": "B&W画像はしばしばより良いコントラストを持ち、ウォーターマークがより見えやすくなります。",
    "learn.bwTip3": "ファイルサイズ削減",
    "learn.bwTip3Desc": "グレースケール画像は通常、カラー画像よりもファイルサイズが小さくなります。",
    "learn.faq1Q": "ウォーターマークを削除できますか？",
    "learn.faq1A":
      "いいえ。MarkVaultはウォーターマークを画像データに永続的に埋め込みます。画像を破壊することなく削除することはできません。",
    "learn.faq2Q": "画像データはサーバーに保存されていますか？",
    "learn.faq2A": "いいえ。すべての処理はデバイス上で行われます。画像はコンピュータを離れません。",
    "learn.faq3Q": "どの画像形式がサポートされていますか？",
    "learn.faq3A": "MarkVaultはJPG、PNG、GIF、WebP、SVG形式をサポートしています。最大ファイルサイズは10MBです。",
    "learn.faq4Q": "MarkVaultをオフラインで使用できますか？",
    "learn.faq4A": "はい。読み込み後、MarkVaultは完全にオフラインで動作します。インターネット接続は不要です。",
    "learn.faq5Q": "適切なウォーターマークテキストを選択するにはどうすればよいですか？",
    "learn.faq5A":
      "名前、著作権記号、ウェブサイトURL、または会社名を使用します。可視性を高めるために短くしてください。",
  },
  zh: {
    "app.title": "MarkVault",
    "app.subtitle": "具有智能水印功能的专业图像保护",
    "upload.title": "上传图像",
    "upload.drag": "将您的图像拖放到此处",
    "upload.click": "或点击浏览",
    "upload.error.type": "请上传有效的图像文件 (JPG、PNG、GIF、WebP、SVG)",
    "upload.error.size": "文件大小必须小于 10MB",
    "edit.title": "编辑图像",
    "preview.title": "预览",
    "preview.download": "下载受保护的图像",
    "bw.label": "转换为黑白",
    "watermark.label": "添加水印图案",
    "watermark.text": "水印文本",
    "watermark.fontSize": "字体大小",
    "watermark.color": "水印颜色",
    "watermark.opacity": "不透明度",
    "watermark.gap": "水印之间的间距",
    "watermark.rotation": "旋转角度",
    "watermark.offsetX": "偏移 X",
    "watermark.offsetY": "偏移 Y",
    "watermark.note": "水印永久嵌入到导出的图像中",
    "tab.bw": "黑白",
    "tab.watermark": "水印",
    "common.reset": "重置",
    "landing.badge": "专业图像保护",
    "landing.hero.title": "使用智能水印保护您的图像",
    "landing.hero.subtitle": "添加专业水印并将图像转换为黑白。使用永久嵌入的保护来保护您的视觉内容。",
    "landing.hero.cta": "免费开始",
    "landing.hero.learn": "了解更多",
    "landing.features.title": "强大的功能",
    "landing.features.protection": "永久保护",
    "landing.features.protectionDesc": "水印永久嵌入到您的图像中，确保无法删除或编辑。",
    "landing.features.fast": "闪电般快速",
    "landing.features.fastDesc": "使用我们优化的客户端技术即时处理您的图像。",
    "landing.features.secure": "100% 安全",
    "landing.features.secureDesc": "所有处理都在您的设备上进行。您的图像永远不会离开您的计算机。",
    "landing.features.watermark": "自定义水印",
    "landing.features.watermarkDesc": "创建具有完整自定义选项的对角水印图案。",
    "landing.features.bw": "黑白",
    "landing.features.bwDesc": "一键将您的图像转换为令人惊艳的黑白。",
    "landing.features.multilang": "8 种语言",
    "landing.features.multilangDesc": "提供英文、印度尼西亚文、日文、中文、西班牙文、法文、韩文和越南文。",
    "landing.details.title": "关于 MarkVault",
    "landing.details.description":
      "MarkVault 是一款专业图像保护工具，专为摄影师、内容创作者和想要保护视觉资产的企业设计。通过智能水印和图像处理功能，MarkVault 确保您的图像保持受保护。",
    "landing.details.feature1": "具有可自定义间距和旋转的对角水印图案",
    "landing.details.feature2": "以专业质量将图像转换为黑白",
    "landing.details.feature3": "为全球用户提供多语言支持",
    "landing.details.version": "当前版本",
    "landing.details.released": "发布时间",
    "landing.details.status": "状态",
    "landing.contact.title": "联系我们",
    "landing.contact.subtitle": "有问题或反馈？我们很乐意听到您的意见。发送消息，我们会尽快回复。",
    "landing.contact.name": "您的名字",
    "landing.contact.namePlaceholder": "John Doe",
    "landing.contact.email": "您的电子邮件",
    "landing.contact.emailPlaceholder": "john@example.com",
    "landing.contact.message": "消息",
    "landing.contact.messagePlaceholder": "告诉我们您对 MarkVault 的看法...",
    "landing.contact.send": "发送消息",
    "landing.footer": "© 2025 MarkVault。版权所有。为每个人提供专业的图像保护。",
    "learn.title": "了解更多",
    "learn.subtitle": "MarkVault 的完整文档和指南",
    "learn.gettingStarted": "入门",
    "learn.gettingStartedDesc": "了解如何只需点击几下即可上传图像并应用水印。",
    "learn.watermarkGuide": "水印指南",
    "learn.watermarkGuideDesc": "掌握使用自定义间距和旋转创建专业水印图案的艺术。",
    "learn.bwConversion": "黑白转换",
    "learn.bwConversionDesc": "以专业质量将图像转换为令人惊艳的黑白。",
    "learn.bestPractices": "最佳实践",
    "learn.bestPracticesDesc": "有效保护图像的提示和技巧。",
    "learn.faq": "常见问题",
    "learn.faqDesc": "查找有关 MarkVault 的常见问题的答案。",
    "learn.step1": "步骤 1：上传您的图像",
    "learn.step1Desc": "单击上传区域或拖放您的图像。支持的格式：JPG、PNG、GIF、WebP、SVG。最大文件大小：10MB。",
    "learn.step2": "步骤 2：配置水印",
    "learn.step2Desc": "输入水印文本并使用字体大小、颜色和不透明度设置自定义外观。",
    "learn.step3": "步骤 3：调整图案",
    "learn.step3Desc": "设置水印之间的间距、旋转角度和位置偏移以创建所需的图案。",
    "learn.step4": "步骤 4：应用效果",
    "learn.step4Desc": "可选择将图像转换为黑白以获得经典外观。",
    "learn.step5": "步骤 5：下载",
    "learn.step5Desc": "下载受保护的图像。水印永久嵌入且无法删除。",
    "learn.watermarkTip1": "对角线图案",
    "learn.watermarkTip1Desc": "使用 -45 度旋转创建难以删除的经典对角线水印。",
    "learn.watermarkTip2": "不透明度设置",
    "learn.watermarkTip2Desc": "将不透明度设置为 20-40% 以实现可见保护，而不会模糊图像内容。",
    "learn.watermarkTip3": "自定义间距",
    "learn.watermarkTip3Desc": "根据图像大小和保护需求将间距调整为 50-300px。",
    "learn.bwTip1": "专业外观",
    "learn.bwTip1Desc": "黑白转换为图像赋予永恒的专业外观。",
    "learn.bwTip2": "增强对比度",
    "learn.bwTip2Desc": "B&W 图像通常具有更好的对比度，使水印更清晰可见。",
    "learn.bwTip3": "减少文件大小",
    "learn.bwTip3Desc": "灰度图像的文件大小通常小于彩色图像。",
    "learn.faq1Q": "可以删除水印吗？",
    "learn.faq1A": "不能。MarkVault 将水印永久嵌入到图像数据中。不破坏图像就无法删除它们。",
    "learn.faq2Q": "我的图像数据是否存储在服务器上？",
    "learn.faq2A": "不是。所有处理都在您的设备上进行。您的图像永远不会离开您的计算机。",
    "learn.faq3Q": "支持哪些图像格式？",
    "learn.faq3A": "MarkVault 支持 JPG、PNG、GIF、WebP 和 SVG 格式。最大文件大小为 10MB。",
    "learn.faq4Q": "我可以离线使用 MarkVault 吗？",
    "learn.faq4A": "可以。加载后，MarkVault 完全离线工作。不需要互联网连接。",
    "learn.faq5Q": "如何选择正确的水印文本？",
    "learn.faq5A": "使用您的名字、版权符号、网站 URL 或公司名称。保持简短以获得更好的可见性。",
  },
  es: {
    "app.title": "MarkVault",
    "app.subtitle": "Protección profesional de imágenes con marcas de agua inteligentes",
    "upload.title": "Subir Imagen",
    "upload.drag": "Arrastra y suelta tu imagen aquí",
    "upload.click": "o haz clic para examinar",
    "upload.error.type": "Por favor, sube un archivo de imagen válido (JPG, PNG, GIF, WebP, SVG)",
    "upload.error.size": "El tamaño del archivo debe ser menor a 10MB",
    "edit.title": "Editar Imagen",
    "preview.title": "Vista Previa",
    "preview.download": "Descargar Imagen Protegida",
    "bw.label": "Convertir a Blanco y Negro",
    "watermark.label": "Agregar Patrón de Marca de Agua",
    "watermark.text": "Texto de Marca de Agua",
    "watermark.fontSize": "Tamaño de Fuente",
    "watermark.color": "Color de Marca de Agua",
    "watermark.opacity": "Opacidad",
    "watermark.gap": "Espacio Entre Marcas de Agua",
    "watermark.rotation": "Ángulo de Rotación",
    "watermark.offsetX": "Desplazamiento X",
    "watermark.offsetY": "Desplazamiento Y",
    "watermark.note": "Las marcas de agua se incrustan permanentemente en la imagen exportada",
    "tab.bw": "Blanco y Negro",
    "tab.watermark": "Marca de Agua",
    "common.reset": "Reiniciar",
    "landing.badge": "Protección Profesional de Imágenes",
    "landing.hero.title": "Protege Tus Imágenes con Marcas de Agua Inteligentes",
    "landing.hero.subtitle":
      "Agrega marcas de agua profesionales y convierte imágenes a blanco y negro. Asegura tu contenido visual con protección permanente e incrustada.",
    "landing.hero.cta": "Comenzar Gratis",
    "landing.hero.learn": "Aprende Más",
    "landing.features.title": "Características Poderosas",
    "landing.features.protection": "Protección Permanente",
    "landing.features.protectionDesc":
      "Las marcas de agua se incrustan permanentemente en tus imágenes, asegurando que no puedan ser removidas o editadas.",
    "landing.features.fast": "Rápido como el Rayo",
    "landing.features.fastDesc":
      "Procesa tus imágenes al instante con nuestra tecnología optimizada del lado del cliente.",
    "landing.features.secure": "100% Seguro",
    "landing.features.secureDesc":
      "Todo el procesamiento ocurre en tu dispositivo. Tus imágenes nunca abandonan tu computadora.",
    "landing.features.watermark": "Marcas de Agua Personalizadas",
    "landing.features.watermarkDesc":
      "Crea patrones de marcas de agua diagonales con opciones de personalización completa.",
    "landing.features.bw": "Blanco y Negro",
    "landing.features.bwDesc": "Convierte tus imágenes a un impresionante blanco y negro con un solo clic.",
    "landing.features.multilang": "8 Idiomas",
    "landing.features.multilangDesc":
      "Disponible en inglés, indonesio, japonés, chino, español, francés, coreano y vietnamita.",
    "landing.details.title": "Acerca de MarkVault",
    "landing.details.description":
      "MarkVault es una herramienta profesional de protección de imágenes diseñada para fotógrafos, creadores de contenido y empresas que desean salvaguardar sus activos visuales. Con capacidades de marcas de agua inteligentes y procesamiento de imágenes, MarkVault asegura que tus imágenes permanezcan protegidas.",
    "landing.details.feature1": "Patrones de marcas de agua diagonales con espaciado y rotación personalizables",
    "landing.details.feature2": "Convierte imágenes a blanco y negro con calidad profesional",
    "landing.details.feature3": "Soporte multiidioma para usuarios globales",
    "landing.details.version": "Versión Actual",
    "landing.details.released": "Lanzado",
    "landing.details.status": "Estado",
    "landing.contact.title": "Ponte en Contacto",
    "landing.contact.subtitle":
      "¿Tienes preguntas o comentarios? Nos encantaría saber de ti. Envíanos un mensaje y responderemos lo antes posible.",
    "landing.contact.name": "Tu Nombre",
    "landing.contact.namePlaceholder": "John Doe",
    "landing.contact.email": "Tu Correo Electrónico",
    "landing.contact.emailPlaceholder": "john@example.com",
    "landing.contact.message": "Mensaje",
    "landing.contact.messagePlaceholder": "Cuéntanos qué piensas sobre MarkVault...",
    "landing.contact.send": "Enviar Mensaje",
    "landing.footer": "© 2025 MarkVault. Todos los derechos reservados. Protección profesional de imágenes para todos.",
    "learn.title": "Aprende Más",
    "learn.subtitle": "Documentación completa y guías para MarkVault",
    "learn.gettingStarted": "Comenzar",
    "learn.gettingStartedDesc": "Aprende cómo subir imágenes y aplicar marcas de agua en solo unos pocos clics.",
    "learn.watermarkGuide": "Guía de Marca de Agua",
    "learn.watermarkGuideDesc":
      "Domina el arte de crear patrones de marcas de agua profesionales con espaciado y rotación personalizados.",
    "learn.bwConversion": "Conversión a Blanco y Negro",
    "learn.bwConversionDesc": "Convierte tus imágenes a un impresionante blanco y negro con calidad profesional.",
    "learn.bestPractices": "Mejores Prácticas",
    "learn.bestPracticesDesc": "Consejos y trucos para proteger tus imágenes de manera efectiva.",
    "learn.faq": "Preguntas Frecuentes",
    "learn.faqDesc": "Encuentra respuestas a preguntas comunes sobre MarkVault.",
    "learn.step1": "Paso 1: Sube Tu Imagen",
    "learn.step1Desc":
      "Haz clic en el área de carga o arrastra y suelta tu imagen. Formatos soportados: JPG, PNG, GIF, WebP, SVG. Tamaño máximo: 10MB.",
    "learn.step2": "Paso 2: Configura la Marca de Agua",
    "learn.step2Desc":
      "Ingresa tu texto de marca de agua y personaliza la apariencia con configuraciones de tamaño de fuente, color y opacidad.",
    "learn.step3": "Paso 3: Ajusta el Patrón",
    "learn.step3Desc":
      "Establece el espacio entre marcas de agua, ángulo de rotación y desplazamientos de posición para crear tu patrón deseado.",
    "learn.step4": "Paso 4: Aplica Efectos",
    "learn.step4Desc": "Opcionalmente convierte tu imagen a blanco y negro para un aspecto clásico.",
    "learn.step5": "Paso 5: Descarga",
    "learn.step5Desc":
      "Descarga tu imagen protegida. Las marcas de agua están incrustadas permanentemente y no se pueden eliminar.",
    "learn.watermarkTip1": "Patrones Diagonales",
    "learn.watermarkTip1Desc":
      "Usa una rotación de -45 grados para marcas de agua diagonales clásicas que son difíciles de eliminar.",
    "learn.watermarkTip2": "Configuración de Opacidad",
    "learn.watermarkTip2Desc":
      "Establece la opacidad entre 20-40% para protección visible sin oscurecer el contenido de la imagen.",
    "learn.watermarkTip3": "Espaciado Personalizado",
    "learn.watermarkTip3Desc":
      "Ajusta el espaciado de 50-300px dependiendo del tamaño de tu imagen y necesidades de protección.",
    "learn.bwTip1": "Aspecto Profesional",
    "learn.bwTip1Desc": "La conversión a blanco y negro da a las imágenes un aspecto atemporal y profesional.",
    "learn.bwTip2": "Contraste Mejorado",
    "learn.bwTip2Desc":
      "Las imágenes en B&N a menudo tienen mejor contraste, haciendo las marcas de agua más visibles.",
    "learn.bwTip3": "Tamaño de Archivo Reducido",
    "learn.bwTip3Desc":
      "Las imágenes en escala de grises típicamente tienen tamaños de archivo más pequeños que las imágenes a color.",
    "learn.faq1Q": "¿Se pueden eliminar las marcas de agua?",
    "learn.faq1A":
      "No. MarkVault incrusta permanentemente las marcas de agua en los datos de la imagen. No se pueden eliminar sin destruir la imagen.",
    "learn.faq2Q": "¿Se almacenan mis datos de imagen en servidores?",
    "learn.faq2A": "No. Todo el procesamiento ocurre en tu dispositivo. Tus imágenes nunca abandonan tu computadora.",
    "learn.faq3Q": "¿Qué formatos de imagen son compatibles?",
    "learn.faq3A": "MarkVault soporta formatos JPG, PNG, GIF, WebP y SVG. El tamaño máximo de archivo es 10MB.",
    "learn.faq4Q": "¿Puedo usar MarkVault sin conexión?",
    "learn.faq4A":
      "Sí. Una vez cargado, MarkVault funciona completamente sin conexión. No se requiere conexión a Internet.",
    "learn.faq5Q": "¿Cómo elijo el texto de marca de agua correcto?",
    "learn.faq5A":
      "Usa tu nombre, símbolo de derechos de autor, URL del sitio web o nombre de la empresa. Mantenlo corto para mejor visibilidad.",
  },
  fr: {
    "app.title": "MarkVault",
    "app.subtitle": "Protection professionnelle des images avec filigrane intelligent",
    "upload.title": "Télécharger une Image",
    "upload.drag": "Glissez-déposez votre image ici",
    "upload.click": "ou cliquez pour parcourir",
    "upload.error.type": "Veuillez télécharger un fichier image valide (JPG, PNG, GIF, WebP, SVG)",
    "upload.error.size": "La taille du fichier doit être inférieure à 10 Mo",
    "edit.title": "Modifier l'Image",
    "preview.title": "Aperçu",
    "preview.download": "Télécharger l'Image Protégée",
    "bw.label": "Convertir en Noir et Blanc",
    "watermark.label": "Ajouter un Motif de Filigrane",
    "watermark.text": "Texte du Filigrane",
    "watermark.fontSize": "Taille de Police",
    "watermark.color": "Couleur du Filigrane",
    "watermark.opacity": "Opacité",
    "watermark.gap": "Espacement Entre les Filigranes",
    "watermark.rotation": "Angle de Rotation",
    "watermark.offsetX": "Décalage X",
    "watermark.offsetY": "Décalage Y",
    "watermark.note": "Les filigranes sont intégrés de manière permanente dans l'image exportée",
    "tab.bw": "Noir et Blanc",
    "tab.watermark": "Filigrane",
    "common.reset": "Réinitialiser",
    "landing.badge": "Protection Professionnelle des Images",
    "landing.hero.title": "Protégez Vos Images avec des Filigranes Intelligents",
    "landing.hero.subtitle":
      "Ajoutez des filigranes professionnels et convertissez les images en noir et blanc. Sécurisez votre contenu visuel avec une protection permanente et intégrée.",
    "landing.hero.cta": "Commencer Gratuitement",
    "landing.hero.learn": "En Savoir Plus",
    "landing.features.title": "Fonctionnalités Puissantes",
    "landing.features.protection": "Protection Permanente",
    "landing.features.protectionDesc":
      "Les filigranes sont intégrés de manière permanente dans vos images, garantissant qu'ils ne peuvent pas être supprimés ou modifiés.",
    "landing.features.fast": "Rapide comme l'Éclair",
    "landing.features.fastDesc": "Traitez vos images instantanément avec notre technologie côté client optimisée.",
    "landing.features.secure": "100% Sécurisé",
    "landing.features.secureDesc":
      "Tout le traitement se fait sur votre appareil. Vos images ne quittent jamais votre ordinateur.",
    "landing.features.watermark": "Filigranes Personnalisés",
    "landing.features.watermarkDesc":
      "Créez des motifs de filigranes diagonaux avec des options de personnalisation complètes.",
    "landing.features.bw": "Noir et Blanc",
    "landing.features.bwDesc": "Convertissez vos images en un magnifique noir et blanc en un seul clic.",
    "landing.features.multilang": "8 Langues",
    "landing.features.multilangDesc":
      "Disponible en anglais, indonésien, japonais, chinois, espagnol, français, coréen et vietnamien.",
    "landing.details.title": "À Propos de MarkVault",
    "landing.details.description":
      "MarkVault est un outil professionnel de protection d'images conçu pour les photographes, les créateurs de contenu et les entreprises qui souhaitent protéger leurs actifs visuels. Avec des capacités de filigrane intelligent et de traitement d'images, MarkVault garantit que vos images restent protégées.",
    "landing.details.feature1": "Motifs de filigranes diagonaux avec espacement et rotation personnalisables",
    "landing.details.feature2": "Convertissez les images en noir et blanc avec une qualité professionnelle",
    "landing.details.feature3": "Support multilingue pour les utilisateurs mondiaux",
    "landing.details.version": "Version Actuelle",
    "landing.details.released": "Publié",
    "landing.details.status": "Statut",
    "landing.contact.title": "Nous Contacter",
    "landing.contact.subtitle":
      "Vous avez des questions ou des commentaires ? Nous aimerions vous entendre. Envoyez-nous un message et nous vous répondrons dès que possible.",
    "landing.contact.name": "Votre Nom",
    "landing.contact.namePlaceholder": "John Doe",
    "landing.contact.email": "Votre Email",
    "landing.contact.emailPlaceholder": "john@example.com",
    "landing.contact.message": "Message",
    "landing.contact.messagePlaceholder": "Dites-nous ce que vous pensez de MarkVault...",
    "landing.contact.send": "Envoyer le Message",
    "landing.footer": "© 2025 MarkVault. Tous droits réservés. Protection professionnelle des images pour tous.",
    "learn.title": "En Savoir Plus",
    "learn.subtitle": "Documentation complète et guides pour MarkVault",
    "learn.gettingStarted": "Commencer",
    "learn.gettingStartedDesc": "Apprenez à télécharger des images et à appliquer des filigranes en quelques clics.",
    "learn.watermarkGuide": "Guide du Filigrane",
    "learn.watermarkGuideDesc":
      "Maîtrisez l'art de créer des motifs de filigranes professionnels avec espacement et rotation personnalisés.",
    "learn.bwConversion": "Conversion Noir et Blanc",
    "learn.bwConversionDesc":
      "Convertissez vos images en un magnifique noir et blanc avec une qualité professionnelle.",
    "learn.bestPractices": "Meilleures Pratiques",
    "learn.bestPracticesDesc": "Conseils et astuces pour protéger vos images efficacement.",
    "learn.faq": "Questions Fréquemment Posées",
    "learn.faqDesc": "Trouvez des réponses aux questions courantes sur MarkVault.",
    "learn.step1": "Étape 1 : Téléchargez Votre Image",
    "learn.step1Desc":
      "Cliquez sur la zone de téléchargement ou glissez-déposez votre image. Formats supportés : JPG, PNG, GIF, WebP, SVG. Taille maximale : 10MB.",
    "learn.step2": "Étape 2 : Configurez le Filigrane",
    "learn.step2Desc":
      "Entrez votre texte de filigrane et personnalisez l'apparence avec les paramètres de taille de police, couleur et opacité.",
    "learn.step3": "Étape 3 : Ajustez le Motif",
    "learn.step3Desc":
      "Définissez l'espacement entre les filigranes, l'angle de rotation et les décalages de position pour créer votre motif souhaité.",
    "learn.step4": "Étape 4 : Appliquez les Effets",
    "learn.step4Desc": "Convertissez optionnellement votre image en noir et blanc pour un aspect classique.",
    "learn.step5": "Étape 5 : Téléchargez",
    "learn.step5Desc":
      "Téléchargez votre image protégée. Les filigranes sont intégrés de manière permanente et ne peuvent pas être supprimés.",
    "learn.watermarkTip1": "Motifs Diagonaux",
    "learn.watermarkTip1Desc":
      "Utilisez une rotation de -45 degrés pour les filigranes diagonaux classiques difficiles à supprimer.",
    "learn.watermarkTip2": "Paramètres d'Opacité",
    "learn.watermarkTip2Desc":
      "Définissez l'opacité entre 20-40% pour une protection visible sans obscurcir le contenu de l'image.",
    "learn.watermarkTip3": "Espacement Personnalisé",
    "learn.watermarkTip3Desc":
      "Ajustez l'espacement de 50-300px selon la taille de votre image et vos besoins de protection.",
    "learn.bwTip1": "Aspect Professionnel",
    "learn.bwTip1Desc": "La conversion en noir et blanc donne aux images un aspect intemporel et professionnel.",
    "learn.bwTip2": "Contraste Amélioré",
    "learn.bwTip2Desc": "Les images en N&B ont souvent un meilleur contraste, rendant les filigranes plus visibles.",
    "learn.bwTip3": "Taille de Fichier Réduite",
    "learn.bwTip3Desc":
      "Les images en niveaux de gris ont généralement des tailles de fichier plus petites que les images en couleur.",
    "learn.faq1Q": "Les filigranes peuvent-ils être supprimés ?",
    "learn.faq1A":
      "Non. MarkVault intègre de manière permanente les filigranes dans les données d'image. Ils ne peuvent pas être supprimés sans détruire l'image.",
    "learn.faq2Q": "Mes données d'image sont-elles stockées sur des serveurs ?",
    "learn.faq2A":
      "Non. Tout le traitement se fait sur votre appareil. Vos images ne quittent jamais votre ordinateur.",
    "learn.faq3Q": "Quels formats d'image sont supportés ?",
    "learn.faq3A": "MarkVault supporte les formats JPG, PNG, GIF, WebP et SVG. La taille maximale du fichier est 10MB.",
    "learn.faq4Q": "Puis-je utiliser MarkVault hors ligne ?",
    "learn.faq4A":
      "Oui. Une fois chargé, MarkVault fonctionne complètement hors ligne. Aucune connexion Internet requise.",
    "learn.faq5Q": "Comment choisir le bon texte de filigrane ?",
    "learn.faq5A":
      "Utilisez votre nom, symbole de droit d'auteur, URL du site Web ou nom de l'entreprise. Gardez-le court pour une meilleure visibilité.",
  },
  ko: {
    "app.title": "MarkVault",
    "app.subtitle": "지능형 워터마크를 갖춘 전문적인 이미지 보호",
    "upload.title": "이미지 업로드",
    "upload.drag": "여기에 이미지를 드래그 앤 드롭하세요",
    "upload.click": "또는 클릭하여 찾아보기",
    "upload.error.type": "유효한 이미지 파일을 업로드하세요 (JPG, PNG, GIF, WebP, SVG)",
    "upload.error.size": "파일 크기는 10MB 미만이어야 합니다",
    "edit.title": "이미지 편집",
    "preview.title": "미리보기",
    "preview.download": "보호된 이미지 다운로드",
    "bw.label": "흑백으로 변환",
    "watermark.label": "워터마크 패턴 추가",
    "watermark.text": "워터마크 텍스트",
    "watermark.fontSize": "글꼴 크기",
    "watermark.color": "워터마크 색상",
    "watermark.opacity": "불투명도",
    "watermark.gap": "워터마크 간격",
    "watermark.rotation": "회전 각도",
    "watermark.offsetX": "오프셋 X",
    "watermark.offsetY": "오프셋 Y",
    "watermark.note": "워터마크는 내보낸 이미지에 영구적으로 포함됩니다",
    "tab.bw": "흑백",
    "tab.watermark": "워터마크",
    "common.reset": "재설정",
    "landing.badge": "전문적인 이미지 보호",
    "landing.hero.title": "지능형 워터마크로 이미지 보호",
    "landing.hero.subtitle":
      "전문적인 워터마크를 추가하고 이미지를 흑백으로 변환하세요. 영구적으로 포함된 보호로 시각적 콘텐츠를 보호하세요.",
    "landing.hero.cta": "무료로 시작",
    "landing.hero.learn": "자세히 알아보기",
    "landing.features.title": "강력한 기능",
    "landing.features.protection": "영구적 보호",
    "landing.features.protectionDesc": "워터마크는 이미지에 영구적으로 포함되어 제거하거나 편집할 수 없습니다.",
    "landing.features.fast": "번개 같은 속도",
    "landing.features.fastDesc": "최적화된 클라이언트 측 기술로 이미지를 즉시 처리하세요.",
    "landing.features.secure": "100% 안전",
    "landing.features.secureDesc": "모든 처리는 장치에서 수행됩니다. 이미지는 컴퓨터를 떠나지 않습니다.",
    "landing.features.watermark": "사용자 정의 워터마크",
    "landing.features.watermarkDesc": "완전한 사용자 정의 옵션이 있는 대각선 워터마크 패턴을 만드세요.",
    "landing.features.bw": "흑백",
    "landing.features.bwDesc": "한 번의 클릭으로 이미지를 멋진 흑백으로 변환하세요.",
    "landing.features.multilang": "8개 언어",
    "landing.features.multilangDesc":
      "영어, 인도네시아어, 일본어, 중국어, 스페인어, 프랑스어, 한국어 및 베트남어로 제공됩니다.",
    "landing.details.title": "MarkVault 정보",
    "landing.details.description":
      "MarkVault는 사진작가, 콘텐츠 제작자 및 시각적 자산을 보호하려는 비즈니스를 위해 설계된 전문적인 이미지 보호 도구입니다. 지능형 워터마크 및 이미지 처리 기능을 통해 MarkVault는 이미지를 보호합니다.",
    "landing.details.feature1": "사용자 정의 가능한 간격 및 회전이 있는 대각선 워터마크 패턴",
    "landing.details.feature2": "전문적인 품질로 이미지를 흑백으로 변환",
    "landing.details.feature3": "전 세계 사용자를 위한 다국어 지원",
    "landing.details.version": "현재 버전",
    "landing.details.released": "출시됨",
    "landing.details.status": "상태",
    "landing.contact.title": "문의하기",
    "landing.contact.subtitle":
      "질문이나 피드백이 있으신가요? 의견을 듣고 싶습니다. 메시지를 보내주시면 최대한 빨리 답변하겠습니다.",
    "landing.contact.name": "이름",
    "landing.contact.namePlaceholder": "John Doe",
    "landing.contact.email": "이메일",
    "landing.contact.emailPlaceholder": "john@example.com",
    "landing.contact.message": "메시지",
    "landing.contact.messagePlaceholder": "MarkVault에 대해 어떻게 생각하는지 알려주세요...",
    "landing.contact.send": "메시지 보내기",
    "landing.footer": "© 2025 MarkVault. 모든 권리 보유. 모두를 위한 전문적인 이미지 보호.",
    "learn.title": "자세히 알아보기",
    "learn.subtitle": "MarkVault의 완전한 문서 및 가이드",
    "learn.gettingStarted": "시작하기",
    "learn.gettingStartedDesc": "단 몇 번의 클릭으로 이미지를 업로드하고 워터마크를 적용하는 방법을 알아봅니다.",
    "learn.watermarkGuide": "워터마크 가이드",
    "learn.watermarkGuideDesc":
      "사용자 정의 간격 및 회전을 사용하여 전문적인 워터마크 패턴을 만드는 기술을 습득합니다.",
    "learn.bwConversion": "흑백 변환",
    "learn.bwConversionDesc": "전문적인 품질로 이미지를 멋진 흑백으로 변환합니다.",
    "learn.bestPractices": "모범 사례",
    "learn.bestPracticesDesc": "이미지를 효과적으로 보호하기 위한 팁과 요령입니다.",
    "learn.faq": "자주 묻는 질문",
    "learn.faqDesc": "MarkVault에 대한 일반적인 질문의 답변을 찾습니다.",
    "learn.step1": "단계 1: 이미지 업로드",
    "learn.step1Desc":
      "업로드 영역을 클릭하거나 이미지를 드래그 앤 드롭합니다. 지원되는 형식: JPG, PNG, GIF, WebP, SVG. 최대 파일 크기: 10MB.",
    "learn.step2": "단계 2: 워터마크 구성",
    "learn.step2Desc": "워터마크 텍스트를 입력하고 글꼴 크기, 색상 및 불투명도 설정으로 모양을 사용자 정의합니다.",
    "learn.step3": "단계 3: 패턴 조정",
    "learn.step3Desc": "워터마크 간격, 회전 각도 및 위치 오프셋을 설정하여 원하는 패턴을 만듭니다.",
    "learn.step4": "단계 4: 효과 적용",
    "learn.step4Desc": "선택적으로 이미지를 흑백으로 변환하여 클래식한 모양을 만듭니다.",
    "learn.step5": "단계 5: 다운로드",
    "learn.step5Desc": "보호된 이미지를 다운로드합니다. 워터마크는 영구적으로 포함되어 있으며 제거할 수 없습니다.",
    "learn.watermarkTip1": "대각선 패턴",
    "learn.watermarkTip1Desc": "-45도 회전을 사용하여 제거하기 어려운 클래식 대각선 워터마크를 만듭니다.",
    "learn.watermarkTip2": "불투명도 설정",
    "learn.watermarkTip2Desc":
      "불투명도를 20-40%로 설정하여 이미지 콘텐츠를 흐리게 하지 않으면서 눈에 띄는 보호를 제공합니다.",
    "learn.watermarkTip3": "사용자 정의 간격",
    "learn.watermarkTip3Desc": "이미지 크기 및 보호 요구 사항에 따라 간격을 50-300px로 조정합니다.",
    "learn.bwTip1": "전문적인 모양",
    "learn.bwTip1Desc": "흑백 변환은 이미지에 시대를 초월한 전문적인 모양을 제공합니다.",
    "learn.bwTip2": "향상된 대비",
    "learn.bwTip2Desc": "B&W 이미지는 종종 더 나은 대비를 가지고 있어 워터마크가 더 잘 보입니다.",
    "learn.bwTip3": "파일 크기 감소",
    "learn.bwTip3Desc": "그레이스케일 이미지는 일반적으로 컬러 이미지보다 파일 크기가 작습니다.",
    "learn.faq1Q": "워터마크를 제거할 수 있습니까?",
    "learn.faq1A":
      "아니요. MarkVault는 워터마크를 이미지 데이터에 영구적으로 포함합니다. 이미지를 파괴하지 않고는 제거할 수 없습니다.",
    "learn.faq2Q": "내 이미지 데이터가 서버에 저장됩니까?",
    "learn.faq2A": "아니요. 모든 처리는 장치에서 수행됩니다. 이미지는 컴퓨터를 떠나지 않습니다.",
    "learn.faq3Q": "어떤 이미지 형식이 지원됩니까?",
    "learn.faq3A": "MarkVault는 JPG, PNG, GIF, WebP 및 SVG 형식을 지원합니다. 최대 파일 크기는 10MB입니다.",
    "learn.faq4Q": "MarkVault를 오프라인으로 사용할 수 있습니까?",
    "learn.faq4A": "예. 로드된 후 MarkVault는 완전히 오프라인으로 작동합니다. 인터넷 연결이 필요하지 않습니다.",
    "learn.faq5Q": "올바른 워터마크 텍스트를 선택하려면 어떻게 해야 합니까?",
    "learn.faq5A":
      "이름, 저작권 기호, 웹사이트 URL 또는 회사 이름을 사용합니다. 더 나은 가시성을 위해 짧게 유지합니다.",
  },
  vi: {
    "app.title": "MarkVault",
    "app.subtitle": "Bảo vệ hình ảnh chuyên nghiệp với hình mờ thông minh",
    "upload.title": "Tải Lên Hình Ảnh",
    "upload.drag": "Kéo và thả hình ảnh của bạn vào đây",
    "upload.click": "hoặc nhấp để duyệt",
    "upload.error.type": "Vui lòng tải lên tệp hình ảnh hợp lệ (JPG, PNG, GIF, WebP, SVG)",
    "upload.error.size": "Kích thước tệp phải nhỏ hơn 10MB",
    "edit.title": "Chỉnh Sửa Hình Ảnh",
    "preview.title": "Xem Trước",
    "preview.download": "Tải Xuống Hình Ảnh Được Bảo Vệ",
    "bw.label": "Chuyển Đổi Thành Đen Trắng",
    "watermark.label": "Thêm Mẫu Hình Mờ",
    "watermark.text": "Văn Bản Hình Mờ",
    "watermark.fontSize": "Kích Thước Phông Chữ",
    "watermark.color": "Màu Hình Mờ",
    "watermark.opacity": "Độ Mờ",
    "watermark.gap": "Khoảng Cách Giữa Các Hình Mờ",
    "watermark.rotation": "Góc Xoay",
    "watermark.offsetX": "Dịch Chuyển X",
    "watermark.offsetY": "Dịch Chuyển Y",
    "watermark.note": "Hình mờ được nhúng vĩnh viễn trong hình ảnh được xuất",
    "tab.bw": "Đen Trắng",
    "tab.watermark": "Hình Mờ",
    "common.reset": "Đặt Lại",
    "landing.badge": "Bảo Vệ Hình Ảnh Chuyên Nghiệp",
    "landing.hero.title": "Bảo Vệ Hình Ảnh Của Bạn Bằng Hình Mờ Thông Minh",
    "landing.hero.subtitle":
      "Thêm hình mờ chuyên nghiệp và chuyển đổi hình ảnh thành đen trắng. Bảo vệ nội dung hình ảnh của bạn bằng bảo vệ vĩnh viễn được nhúng.",
    "landing.hero.cta": "Bắt Đầu Miễn Phí",
    "landing.hero.learn": "Tìm Hiểu Thêm",
    "landing.features.title": "Các Tính Năng Mạnh Mẽ",
    "landing.features.protection": "Bảo Vệ Vĩnh Viễn",
    "landing.features.protectionDesc":
      "Hình mờ được nhúng vĩnh viễn trong hình ảnh của bạn, đảm bảo không thể xóa hoặc chỉnh sửa.",
    "landing.features.fast": "Nhanh Như Tia Chớp",
    "landing.features.fastDesc":
      "Xử lý hình ảnh của bạn ngay lập tức với công nghệ phía máy khách được tối ưu hóa của chúng tôi.",
    "landing.features.secure": "100% An Toàn",
    "landing.features.secureDesc":
      "Tất cả xử lý diễn ra trên thiết bị của bạn. Hình ảnh của bạn không bao giờ rời khỏi máy tính của bạn.",
    "landing.features.watermark": "Hình Mờ Tùy Chỉnh",
    "landing.features.watermarkDesc": "Tạo các mẫu hình mờ đường chéo với các tùy chọn tùy chỉnh đầy đủ.",
    "landing.features.bw": "Đen Trắng",
    "landing.features.bwDesc": "Chuyển đổi hình ảnh của bạn thành đen trắng tuyệt đẹp chỉ bằng một cú nhấp chuột.",
    "landing.features.multilang": "8 Ngôn Ngữ",
    "landing.features.multilangDesc":
      "Có sẵn bằng tiếng Anh, Indonesia, Nhật, Trung Quốc, Tây Ban Nha, Pháp, Hàn Quốc và Việt Nam.",
    "landing.details.title": "Về MarkVault",
    "landing.details.description":
      "MarkVault là một công cụ bảo vệ hình ảnh chuyên nghiệp được thiết kế cho các nhiếp ảnh gia, người sáng tạo nội dung và các doanh nghiệp muốn bảo vệ tài sản hình ảnh của họ. Với khả năng hình mờ thông minh và xử lý hình ảnh, MarkVault đảm bảo hình ảnh của bạn vẫn được bảo vệ.",
    "landing.details.feature1": "Các mẫu hình mờ đường chéo với khoảng cách và xoay có thể tùy chỉnh",
    "landing.details.feature2": "Chuyển đổi hình ảnh thành đen trắng với chất lượng chuyên nghiệp",
    "landing.details.feature3": "Hỗ trợ đa ngôn ngữ cho người dùng toàn cầu",
    "landing.details.version": "Phiên Bản Hiện Tại",
    "landing.details.released": "Phát Hành",
    "landing.details.status": "Trạng Thái",
    "landing.contact.title": "Liên Hệ Với Chúng Tôi",
    "landing.contact.subtitle":
      "Có câu hỏi hoặc phản hồi? Chúng tôi rất muốn nghe từ bạn. Gửi cho chúng tôi một tin nhắn và chúng tôi sẽ phản hồi sớm nhất có thể.",
    "landing.contact.name": "Tên Của Bạn",
    "landing.contact.namePlaceholder": "John Doe",
    "landing.contact.email": "Email Của Bạn",
    "landing.contact.emailPlaceholder": "john@example.com",
    "landing.contact.message": "Tin Nhắn",
    "landing.contact.messagePlaceholder": "Cho chúng tôi biết bạn nghĩ gì về MarkVault...",
    "landing.contact.send": "Gửi Tin Nhắn",
    "landing.footer": "© 2025 MarkVault. Bảo lưu mọi quyền. Bảo vệ hình ảnh chuyên nghiệp cho mọi người.",
    "learn.title": "Tìm Hiểu Thêm",
    "learn.subtitle": "Tài liệu đầy đủ và hướng dẫn cho MarkVault",
    "learn.gettingStarted": "Bắt Đầu",
    "learn.gettingStartedDesc": "Tìm hiểu cách tải lên hình ảnh và áp dụng hình mờ chỉ trong vài cú nhấp chuột.",
    "learn.watermarkGuide": "Hướng Dẫn Hình Mờ",
    "learn.watermarkGuideDesc":
      "Nắm vững nghệ thuật tạo các mẫu hình mờ chuyên nghiệp với khoảng cách và xoay tùy chỉnh.",
    "learn.bwConversion": "Chuyển Đổi Đen Trắng",
    "learn.bwConversionDesc": "Chuyển đổi hình ảnh của bạn thành đen trắng tuyệt đẹp với chất lượng chuyên nghiệp.",
    "learn.bestPractices": "Thực Hành Tốt Nhất",
    "learn.bestPracticesDesc": "Mẹo và thủ thuật để bảo vệ hình ảnh của bạn một cách hiệu quả.",
    "learn.faq": "Câu Hỏi Thường Gặp",
    "learn.faqDesc": "Tìm câu trả lời cho các câu hỏi phổ biến về MarkVault.",
    "learn.step1": "Bước 1: Tải Lên Hình Ảnh Của Bạn",
    "learn.step1Desc":
      "Nhấp vào khu vực tải lên hoặc kéo và thả hình ảnh của bạn. Định dạng được hỗ trợ: JPG, PNG, GIF, WebP, SVG. Kích thước tệp tối đa: 10MB.",
    "learn.step2": "Bước 2: Cấu Hình Hình Mờ",
    "learn.step2Desc":
      "Nhập văn bản hình mờ của bạn và tùy chỉnh giao diện bằng cách sử dụng cài đặt kích thước phông chữ, màu sắc và độ mờ.",
    "learn.step3": "Bước 3: Điều Chỉnh Mẫu",
    "learn.step3Desc": "Đặt khoảng cách giữa các hình mờ, góc xoay và độ lệch vị trí để tạo mẫu mong muốn.",
    "learn.step4": "Bước 4: Áp Dụng Hiệu Ứng",
    "learn.step4Desc": "Tùy chọn chuyển đổi hình ảnh của bạn thành đen trắng để có giao diện cổ điển.",
    "learn.step5": "Bước 5: Tải Xuống",
    "learn.step5Desc": "Tải xuống hình ảnh được bảo vệ của bạn. Hình mờ được nhúng vĩnh viễn và không thể xóa được.",
    "learn.watermarkTip1": "Mẫu Đường Chéo",
    "learn.watermarkTip1Desc": "Sử dụng xoay -45 độ cho hình mờ đường chéo cổ điển khó xóa.",
    "learn.watermarkTip2": "Cài Đặt Độ Mờ",
    "learn.watermarkTip2Desc": "Đặt độ mờ từ 20-40% để bảo vệ rõ ràng mà không làm mờ nội dung hình ảnh.",
    "learn.watermarkTip3": "Khoảng Cách Tùy Chỉnh",
    "learn.watermarkTip3Desc":
      "Điều chỉnh khoảng cách từ 50-300px tùy thuộc vào kích thước hình ảnh và nhu cầu bảo vệ của bạn.",
    "learn.bwTip1": "Giao Diện Chuyên Nghiệp",
    "learn.bwTip1Desc": "Chuyển đổi đen trắng mang lại cho hình ảnh một giao diện chuyên nghiệp vượt thời gian.",
    "learn.bwTip2": "Tương Phản Được Cải Thiện",
    "learn.bwTip2Desc": "Hình ảnh B&W thường có tương phản tốt hơn, làm cho hình mờ dễ nhìn hơn.",
    "learn.bwTip3": "Giảm Kích Thước Tệp",
    "learn.bwTip3Desc": "Hình ảnh thang xám thường có kích thước tệp nhỏ hơn hình ảnh màu.",
    "learn.faq1Q": "Có thể xóa hình mờ không?",
    "learn.faq1A":
      "Không. MarkVault nhúng vĩnh viễn hình mờ vào dữ liệu hình ảnh. Chúng không thể bị xóa mà không phá hủy hình ảnh.",
    "learn.faq2Q": "Dữ liệu hình ảnh của tôi có được lưu trữ trên máy chủ không?",
    "learn.faq2A":
      "Không. Tất cả xử lý diễn ra trên thiết bị của bạn. Hình ảnh của bạn không bao giờ rời khỏi máy tính của bạn.",
    "learn.faq3Q": "Những định dạng hình ảnh nào được hỗ trợ?",
    "learn.faq3A": "MarkVault hỗ trợ các định dạng JPG, PNG, GIF, WebP và SVG. Kích thước tệp tối đa là 10MB.",
    "learn.faq4Q": "Tôi có thể sử dụng MarkVault ngoại tuyến không?",
    "learn.faq4A": "Có. Sau khi tải, MarkVault hoạt động hoàn toàn ngoại tuyến. Không cần kết nối Internet.",
    "learn.faq5Q": "Làm cách nào để chọn văn bản hình mờ phù hợp?",
    "learn.faq5A":
      "Sử dụng tên của bạn, ký hiệu bản quyền, URL trang web hoặc tên công ty. Giữ nó ngắn để dễ nhìn hơn.",
  },
}

export function LanguageProvider({ children }: React.ReactNode) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["en"]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
